// Custom Action DLL to find Mixxx installations regardless of install scope.
// The standard MSI FindRelatedProducts skips per-user installs when the
// current install is per-machine. This includes the mismatch generated by
// CPACK_WIX_INSTALL_SCOPE "none".
// This MsiEnumRelatedProducts() has no such filter.

// clang-format off
// windows.h must precede msi.h (defines UINT, WINAPI, etc.)
#include <windows.h>
#include <msi.h>
#include <msiquery.h>
// clang-format on

#pragma comment(lib, "msi.lib")

namespace {
// MSI GUIDs are exactly 38 chars (incl curly brackets, dashes and the null terminator):
// {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
constexpr DWORD kMsiGuidBufferSize = 39;

// Mixxx Upgrade GUID — same as CPACK_WIX_UPGRADE_GUID
// Custom "Andy's Mixxx" build: distinct UpgradeCode so it installs alongside
// the official Mixxx instead of removing it. Only ever removes OTHER copies of
// this custom build, never the upstream one.
constexpr wchar_t kMixxxUpgradeCode[] = L"{895F2517-9556-4A29-827E-5CCE24E28A14}";
} // namespace

extern "C"
        __declspec(dllexport) UINT __stdcall FindAllRelatedMixxxInstallations(
                MSIHANDLE hInstall) {
    // Get our own ProductCode so we don't mark ourselves for removal.
    wchar_t productCode[kMsiGuidBufferSize] = {};
    DWORD productCodeLen = kMsiGuidBufferSize;
    MsiGetPropertyW(hInstall, L"ProductCode", productCode, &productCodeLen);

    // Enumerate ALL products with our UpgradeCode (scope-agnostic).
    wchar_t relatedProduct[kMsiGuidBufferSize] = {};
    DWORD index = 0;
    while (MsiEnumRelatedProductsW(kMixxxUpgradeCode, 0, index, relatedProduct) == ERROR_SUCCESS) {
        if (wcscmp(relatedProduct, productCode) != 0) {
            // Found an older/different installation — mark it for upgrade removal.
            MsiSetPropertyW(hInstall, L"WIX_UPGRADE_DETECTED", relatedProduct);
            MsiSetPropertyW(hInstall, L"MIGRATE", relatedProduct);
            MsiSetPropertyW(hInstall, L"UPGRADINGPRODUCTCODE", relatedProduct);
            break; // Typically only one old installation exists
        }
        ++index;
    }

    return ERROR_SUCCESS;
}
